name: normal
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eval:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix

      - name: Eval "jetson thor".
        run: just ci just eval --host=thor

  build:
    runs-on: ubuntu-24.04-arm
    environment: deploy
    env:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix

      - name: Build "jetson thor".
        run: just ci just build --host=thor

      - name: Upload to 'cachix'.
        run: just ci just upload --host=thor
