name: normal
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Aggregate check for protection rule.
  checks-all:
    if: always()
    needs:
      - build
      - eval
    runs-on: ubuntu-latest
    steps:
      - name: Verify all matrix jobs passed
        run: |
          if [[ "${{ needs.checks.result }}" != "success" ]]; then
            echo "One or more checks failed: ${{ needs.checks.result }}"
            exit 1
          fi

  eval:
    name: eval ${{ matrix.nixos }} (installer=${{ matrix.installer }}, cross=${{ matrix.cross }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nixos:
          - thor-devkit
        installer:
          - "true"
          - "false"
        cross:
          - "true"
          - "false"
        # Only cross-compile the installer; skip cross for the plain system.
        exclude:
          - installer: "false"
            cross: "true"
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix

      - name: Eval "jetson thor".
        run: |
          just ci just eval \
            --nixos=${{ matrix.nixos }} \
            --cross=${{ matrix.cross }} \
            --installer=${{ matrix.installer }}

  build:
    name: build ${{ matrix.nixos }} (installer=${{ matrix.installer }}, cross=${{ matrix.cross }})
    runs-on: ${{ matrix.cross == 'true' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}

    environment: deploy
    strategy:
      fail-fast: false
      matrix:
        nixos:
          - thor-devkit
        installer:
          - "true"
          - "false"
        cross:
          - "true"
          - "false"
        # Only cross-compile the installer; skip cross for the plain system.
        exclude:
          - installer: "false"
            cross: "true"
    env:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix

      - name: Build "${{ matrix.nixos }}".
        run: |
          just ci just build \
            --nixos=${{ matrix.nixos }} \
            --cross=${{ matrix.cross }} \
            --installer=${{ matrix.installer }}

      - name: Upload to 'cachix'.
        if: github.ref == 'refs/heads/main'
        run: |
          just ci just upload \
          --nixos=${{ matrix.nixos }} \
          --cross=${{ matrix.cross }} \
