name: normal
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eval:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        nixos:
          - thor-devkit
          - thor-devkit-installer
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix

      - name: Eval "jetson thor".
        run: just ci just build --nixos=${{ matrix.nixos }}

  build:
    runs-on: ubuntu-24.04-arm
    environment: deploy
    strategy:
      fail-fast: false
      matrix:
        nixos:
          - thor-devkit
    env:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix

      - name: Build "${{ matrix.nixos }}".
        run: just ci just build --nixos=${{ matrix.nixos }}

      - name: Upload to 'cachix'.
        if: github.ref == 'refs/heads/main'
        run: just ci just upload --nixos=${{ matrix.nixos }}

  build-iso:
    runs-on: ubuntu-24.04-arm
    environment: deploy
    strategy:
      fail-fast: false
      matrix:
        nixos:
          - thor-devkit-installer
    env:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix

      - name: Build "${{ matrix.nixos }}".
        run: just ci just build --nixos=${{ matrix.nixos }} --iso

      - name: Upload to 'cachix'.
        if: github.ref == 'refs/heads/main'
        run: just ci just upload --nixos=${{ matrix.nixos }} --iso
